name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20 # Update to a recent Node version
          cache: "yarn" # Cache Yarn dependencies for faster builds
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build the production bundle
        run: |
          release_version=$(cat package.json | jq -r '.version')
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          yarn build
      - name: Verify build output
        run: ls -la dist/ # Debug step to ensure tar.gz is created
      - name: Perform GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ env.RELEASE_VERSION }}
          tag_name: v${{ env.RELEASE_VERSION }}
          generate_release_notes: true
          files: dist/*.tar.gz
